### ISSUE TITLE
Code review: remove pgCheckInput

### ISSUE THREAD

**Issue by rdewijn** [tercen/two_sample_ttest_operator#2]
Remove the dependency on pgCheckInput (and the calls to "check" on line 59-60). Replace with additional checks in the code anyway.

The check for a factor on the x-axis is unnecessary anyway. The operator fails when there is no factor on the x-axis, however this factor is not used in the calculation.

.rowSeq
.colSeq
Grouping = .color
Pairing = .labels

**Comment by ginberg** [comment]
pgCheckInput removed and custom check added
